export const UXUI = [
  {
    name: "Convertio",
    url: "https://convertio.co/",
    description: "Convierte tus archivos a cualquier formato",
    media: "https://i.ibb.co/Rcv3Thw/image.png",
    tags: [
      "convertidor",
      "convert",
      "icon",
      "icons",
      "iconos",
      "imagenes",
      "archivo",
      "archivos",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "Hero Icons",
    url: "https://heroicons.com/",
    description:
      "Hermosos íconos SVG hechos a mano por los creadores de Tailwind CSS.",
    media: "https://i.ibb.co/BGDfBLp/image.png",
    tags: [
      "iconos",
      "icon",
      "icons",
      "hero",
      "heroicons",
      "icons",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "NextUI",
    url: "https://nextui.org/",
    description:
      "Cree sitios web hermosos independientemente de su experiencia en diseño.",
    media: "https://i.ibb.co/FYFMsyS/image.png",
    tags: [
      "componentes",
      "css",
      "next",
      "nextui",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "SVGL",
    url: "https://svgl.app/",
    description: "Todo el svg necesario para crear un buen diseño.",
    media: "https://i.ibb.co/3SKbp0Z/image.png",
    tags: [
      "iconos",
      "icon",
      "icons",
      "svg",
      "svgl",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "DaisyUI",
    url: "https://daisyui.com/",
    description:
      "DaisyUI es un plugin para Tailwind CSS que te permite diseñar fácilmente interfaces de usuario.",
    media: "https://i.ibb.co/wwh8cCF/image.png",
    tags: [
      "componentes",
      "plugin",
      "css",
      "frontend",
      "daisyui",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "Flowbite",
    url: "https://flowbite.com/",
    description: "Flowbite ofrece componentes para crear sitios rápidamente.",
    media: "https://i.ibb.co/y4WPxbL/image.png",
    tags: [
      "componentes",
      "tailwind",
      "css",
      "flowbite",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "UI Colors",
    url: "https://uicolors.app/create",
    description: "Generador de colores para utilizarlos con Tailwind.",
    media: "https://i.ibb.co/7brMYMB/image.png",
    tags: [
      "generador",
      "colors",
      "color",
      "colores",
      "generadores",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "Google Fonts",
    url: "https://fonts.google.com/",
    description: "Google Fonts, no hace falta que diga nada.",
    media: "https://i.ibb.co/Pz79H16/image.png",
    tags: [
      "fuentes",
      "google",
      "fonts",
      "font",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "Unsplash",
    url: "https://unsplash.com/es",
    description:
      "Una gran inmensidad de fondos de pantalla hechos por creadores de todo el mundo.",
    media: "https://i.ibb.co/BCmmpV2/image.png",
    tags: [
      "wallpapers",
      "fotos",
      "calidad",
      "unsplash",
      "fondos",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "Am I Responsive?",
    url: "https://ui.dev/amiresponsive?",
    description: "¿Tu sitio tiene un diseño adaptativo? Podes descubrirlo acá.",
    media: "https://i.ibb.co/sq7Skpf/image.png",
    tags: [
      "utilidades",
      "responsive",
      "responsivo",
      "diseño",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "Real Time Colors",
    url: "https://www.realtimecolors.com/",
    description: "Visualiza colores y fuentes en tiempo real.",
    media: "https://i.ibb.co/wN227G3/image.png",
    tags: [
      "generadores",
      "colores",
      "colors",
      "color",
      "real",
      "time",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "Figma",
    url: "https://www.figma.com/",
    description:
      "La forma en que diseña, planifica y desarrolla es importante. Hazlo en equipo con Figma.",
    media: "https://i.ibb.co/XYQpxs9/image.png",
    tags: [
      "utilidades",
      "diseño",
      "plan",
      "desarrollo",
      "equipo",
      "figma",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "Vercel Templates",
    url: "https://vercel.com/templates",
    description:
      "Inicie el proceso de desarrollo de su aplicación con soluciones prediseñadas de Vercel y nuestra comunidad.",
    media: "https://i.ibb.co/ZKkHb9F/image.png",
    tags: [
      "plantillas",
      "inspiración",
      "vercel",
      "templates",
      "desarrollo",
      "diseño",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
  {
    name: "GTMetrix",
    url: "https://gtmetrix.com/",
    description:
      "GTMetrix le indica cómo funciona su sitio web, por qué es lento y cómo optimizarlo.",
    media: "https://i.ibb.co/gDsY9dp/image.png",
    tags: [
      "utilidades",
      "seo",
      "rendimiento",
      "velocidad",
      "web",
      "ux",
      "ui",
      "uxui",
      "uiux",
      "ux/ui",
      "ui/ux",
    ],
  },
];
